FROM ubuntu:20.04
WORKDIR /opt/app
COPY destroy.sh ./
RUN chmod 755 destroy.sh
RUN apt update && apt install openjdk-17-jdk unzip curl wget -y
RUN wget https://releases.hashicorp.com/terraform/1.5.2/terraform_1.5.2_linux_386.zip
RUN unzip terraform_1.5.2_linux_386.zip
RUN mv terraform /usr/local/bin/
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
RUN rm *.zip